services:
  db:
    image: mysql:8.0
    container_name: stateless_db
    restart: always
    environment:
      MYSQL_DATABASE: stateless_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: stateless_backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: