spring.application.name=stateless
# ... tus otras configuraciones de MySQL y JPA ...

# Spring Mail Configuration
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=tu_usuario
spring.mail.password=tu_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.oauth2.client.registration.google.client-id=TU_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=TU_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# App Config
app.base-url=http://localhost:8080